Repository Activiti/activiti-cloud-query-service, pull requests merged in 2018-11, with the labels that each got.

#111 fix: (model) replace @Lob annotation on VariableValue attribute with TEXT column definition
  activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/VariableEntity.java
Labels: enhancement

#115 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#116 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.40
  pom.xml
Labels: updatebot

#117 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.41
  pom.xml
Labels: updatebot

#121 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.35
  pom.xml
Labels: in progress, updatebot

#123 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  .updatebot.yml
Labels: enhancement, in progress

#125 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.36
  pom.xml
Labels: in progress, updatebot

#124 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.47
  pom.xml
Labels: in progress, updatebot

#122 Handle process deployed event
  activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/ProcessDefinitionEntity.java
  activiti-cloud-services-query/activiti-cloud-services-query-repo/src/main/java/org/activiti/cloud/services/query/app/repository/ProcessDefinitionRepository.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/asciidoc/index.adoc
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/conf/QueryRestAutoConfiguration.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/ProcessDeployedEventHandler.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/resources/ProcessDefinitionResource.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessDefinitionAdminController.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceAdminController.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceController.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceRelProvider.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/QueryRelProvider.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/assembler/ProcessDefinitionResourceAssembler.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/config/QueryRepositoryConfig.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/resources/META-INF/spring.factories
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/events/handlers/ProcessDeployedEventHandlerTest.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/ProcessDefinitionAdminControllerIT.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/QueryRelProviderTest.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryAdminProcessDefinitionIT.java
Labels: in progress

#129 fix: (ITs) use @DirtiesContext annotation for ITs classes
  activiti-cloud-starter-query/pom.xml
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryAdminProcessDefinitionIT.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryAdminVariablesIT.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessInstanceEntityVariablesIT.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessInstancesEntityIT.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryTaskEntityVariablesIT.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryTasksIT.java
Labels: bug, in progress

#126 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.49
  pom.xml
Labels: in progress, updatebot

#127 Add activiti-cloud-query-dependencies-tests module
  activiti-cloud-query-dependencies/pom.xml
  activiti-cloud-services-query/pom.xml
  activiti-cloud-starter-query/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#130 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: in progress, updatebot

#132 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: in progress, updatebot

#134 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: in progress, updatebot

#133 remove bean overriding
  activiti-cloud-starter-query/src/test/resources/application.properties
Labels: in progress

#135 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: in progress, updatebot

#136 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: in progress, updatebot

#138 missed these ones
  activiti-cloud-starter-query/src/test/resources/application-test-admin.properties
  activiti-cloud-starter-query/src/test/resources/application-test.properties
Labels: in progress
