Repository Activiti/activiti-cloud-query-service, pull requests merged in 2018-12, with the labels that each got.

#139 Fix process definitions collection rel name
  Jenkinsfile
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/QueryRelProvider.java
Labels: in progress

#131 feat: ProcessUpdatedEventHandler implemented to support update process events
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/ProcessUpdatedEventHandler.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceAdminController.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskAdminController.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/events/handlers/ProcessUpdatedEventHandlerTest.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/events/handlers/QueryEventHandlerContextIT.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/ProcessInstanceEntityAdminControllerIT.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskEntityAdminControllerIT.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessInstancesEntityIT.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryTasksIT.java
Labels: in progress, ready-for-review

#140 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: in progress, updatebot

#141 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: in progress, updatebot

#142 Set process instance name
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/ProcessStartedEventHandler.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/events/handlers/ProcessStartedEventHandlerTest.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessInstancesEntityIT.java
Labels: in progress

#143 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: in progress, updatebot

#148 fix(versions): update Activiti/activiti-cloud-query-service versions
  activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/ProcessInstanceEntity.java
  pom.xml
Labels: updatebot

#150 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: updatebot

#152 fix(versions): update Activiti/activiti-cloud-query-service versions
  pom.xml
Labels: updatebot
