Repository Activiti/activiti-cloud-query-service, pull requests merged in 2019-11, with the labels that each got.

#326 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#327 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#328 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#329 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#332 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#333 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#334 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#335 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#336 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#337 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#338 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#339 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#340 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#341 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#342 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#343 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#344 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#345 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#346 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#347 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#348 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#350 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#351 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#352 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#353 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#354 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#355 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#356 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot

#357 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryAdminProcessDiagramIT.java
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryProcessDiagramIT.java
  pom.xml
Labels: updatebot

#316 feat(build): Start test containers in parallel
  activiti-cloud-services-query/activiti-cloud-services-query-rest/pom.xml
  activiti-cloud-starter-query/pom.xml
Labels: enhancement

#245 taskDefinitionKey added to TaskEntity
  activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/TaskEntity.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/TaskCreatedEventHandler.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/events/handlers/TaskEntityCreatedEventHandlerTest.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/ProcessInstanceEntityTasksControllerIT.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskEntityAdminControllerIT.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskEntityControllerIT.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TaskEntityDeleteControllerIT.java
  activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/rest/TestTaskEntityBuilder.java
  activiti-cloud-starter-query/src/main/resources/config/query/liquibase/changelog/02-alter.pg.schema.m6.sql
  activiti-cloud-starter-query/src/main/resources/config/query/liquibase/changelog/h2.schema.sql
  activiti-cloud-starter-query/src/main/resources/config/query/liquibase/master.xml
  activiti-cloud-starter-query/src/test/java/org/activiti/cloud/starter/tests/QueryTasksIT.java
  pom.xml
Labels: ready-for-review

#359 fix(versions): update Activiti/activiti-cloud-query-service versions into develop
  pom.xml
Labels: updatebot
